apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cloud-provider-g-eu3
  namespace: provider
  labels:
    app: cloud
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      cloud: Google
      region: europe-west3
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
