apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cloud-provider-az-cus
  namespace: provider
  labels:
    app: cloud
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      cloud: Azure
      region: centralus
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
