apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cloud-azure-centralus
  namespace: provider
  annotations:
    apps.open-cluster-management.io/github-path: cloud-provider/nginx
    apps.open-cluster-management.io/github-branch: cloud-provider
  labels:
    app: cloud
spec:
  channel: demo/gitops
  placement:
    placementRef:
      name: cloud-provider-az-cus
      kind: PlacementRule
  packageOverrides:
  - packageName: kustomization
    packageOverrides:
    - value: |
        namespace: provider
        resources:
        - service.yaml
        - deployment-az-cus.yaml

