apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cloud-amazon-eu-central-1
  namespace: provider
  annotations:
    apps.open-cluster-management.io/github-path: placement/nginx
    apps.open-cluster-management.io/github-branch: cloud-provider
  labels:
    app: cloud
spec:
  channel: demo/gitops
  placement:
    placementRef:
      name: nginx-placement-a-eu1
      kind: PlacementRule
  packageOverrides:
  - packageName: kustomization
    packageOverrides:
    - value: |
        namespace: provider
        resources:
        - service.yaml
        - deployment-a-eu1.yaml

