apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-placement
  labels:
    app.kubernetes.io/name: nginx-a-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-a-3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-a-3
    spec:
      containers:
      - name: nginx
        image: quay.io/jpacker/nginx:1.16.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUD_PROVIDER
          value: "Amazon"
        - name: ZONE
          value: "us-west-3"
        volumeMounts:
          - mountPath: /app/provider
            name: cache-provider
      volumes:
      - name: cache-provider
        emptyDir: {}
